### ISSUE TITLE
[BUG] arabseed next page missing 

### ISSUE THREAD

**Issue by Santaklawz** [zombiB/zombi-addons#147]
1-Describe the bug:
Arabseed series Arabic next page missing 
Wecima and cimanow and cima4u not working 

3-Screenshots:if needed

**Comment by zombiB** [comment]
Arabseed bug fixed thx for sharing
Cima4u domain updated it should work now
Wecima and cimanow re already working for me

**Comment by Santaklawz** [comment]
> Arabseed bug fixed thx for sharing Cima4u domain updated it should work now Wecima and cimanow re already working for me

Arabseed next page is there now but not accurate keeps showing the same information cima4u work now but wecima and cimanow still not working for me it says no information when you choose the site or just does nothing tried with and without VPN

**Comment by zombiB** [comment]
Which section are not working or all of them?
